name: Matrix with Node.js
on:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        version: [14, 16, 17]
        platform: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - platform: ubuntu-latest
            version: 16
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: action/checkout@v2
      - name: Use Node.js ${{ matrix.version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.version }}
      - run: npm install
      - name: Running on Platform = ${{ matrix.platform }} Node = ${{ matrix.version }}
        run: npm test
    continue-on-error: ${{ matrix.version }}
